name: Build on Pull Request

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up C++ 
      uses: aminya/setup-cpp@v1
      with:
        compiler: clang
        cpp-version: 11

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake

    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . -- -j$(nproc)
