name: Build on Pull Request

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up C++ 
      uses: aminya/setup-cpp@v1
      with:
        compiler: clang

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake

    - name: Install Qt
      run: |
        sudo apt-get install -y qt6-base-dev qt6-tools-dev-tools
        sudo apt install libqt5multimedia5
        
    - name: Build the project
      run: |
        cd JetRacer/src/head_unit/cluster_qt
        mkdir build
        cd build
        cmake ..
        cmake --build . -- -j$(nproc)
